aws:
  # Ubuntu 14.04.3 LTS (Trusty Tahr)
  # See https://cloud-images.ubuntu.com/releases/14.04/release-20151117/
  ami               : 'ami-7b89cc11'
  # Replace this with your AWS access key id
  access_key_id     : 'AKXXXXXXXXXXXXXXX'
  # Replace this with your AWS secret access key
  secret_access_key : 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
  # If you have set up your own keypair change this to the name of the key pair
  keypair_name      : 'satellite-image-processing'
  # This security group should at least have port 22 (ssh) access
  security_groups   : [ 'ssh-only' ]
  region            : 'us-east-1'
  # Should point to your private key corresponding to the keypair named above
  pemfile           : '~/.ssh/satellite-image-processing.pem'
  # This instance profile is created by the helper script `create_s3_role.sh`
  # It gives permissions for the EC2 instance to write to all S3 buckets
  # See http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html
  instance_profile  : 'S3-Permissions'
  # See https://aws.amazon.com/ec2/instance-types/
  instance_type     : 'c3.large'

